parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  arrow-parens: warn
  comma-dangle:
    [
      warn,
      {
        arrays: always-multiline,
        objects: always-multiline,
        imports: always-multiline,
        exports: always-multiline,
        functions: always-multiline,
      },
    ]
  curly: [warn, multi-line]
  indent: [warn, 2, {SwitchCase: 1}]
  max-len:
    [
      warn,
      {
        code: 80,
        ignoreRegExpLiterals: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
      },
    ]
  no-irregular-whitespace: error
  no-mixed-spaces-and-tabs: warn
  no-undef: error
  no-unused-vars: warn
  object-curly-spacing: warn
  object-shorthand: warn
  quotes: [warn, single]
  semi: [error, never]
  strict: [error, never]
