cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - public/app.css
    - public/app.js
    - public/vendor.js

stages:
  - build
  - deploy

build:
  stage: build

  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build:prod

deploy:
  stage: deploy

  only:
    - master
  script:
    - >-
      scp
      public/app.css
      public/app.js
      public/vendor.js
      www@gailkirklandphotography.com:/var/www/gailkirklandphotography-www/public
