cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build

  script:
    - npm update
    - npm run build:prod

deploy:
  stage: deploy

  only:
    - master
  script:
    - >-
      scp
      public/app.css
      public/app.js
      public/vendor.js
      www@gailkirklandphotography.com:/var/www/gailkirklandphotography-www/public
