deploy:
  script:
    - npm install
    - npm run build:prod
    - scp -r public/app.js gailkirklandphotography.com:/var/www/gailkirklandphotography.com/public
    - scp -r public/app.css gailkirklandphotography.com:/var/www/gailkirklandphotography.com/public

# TODO: docker
# image: node:latest
#
# TODO: stages
# build:
#   stage: build
#   script:
#     - npm install
#     - npm run build:prod
#
# deploy:
#   stage: deploy
#   script:
#     - scp -r public/app.js gailkirklandphotography.com:/var/www/gailkirklandphotography.com/public
#     - scp -r public/app.css gailkirklandphotography.com:/var/www/gailkirklandphotography.com/public
#   when: on_success
