cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - public/app.css
    - public/app.js
    - public/vendor.js
variables:
  NODE_ENV: production

build:
  stage: build

  script:
    - npm prune --production=false
    - npm install
    - npm install --only=dev
    - npm list --depth=0 --only=prod
    - npm list --depth=0 --only=dev
    - npm run build:prod

deploy:
  stage: deploy

  only:
    - master
  script:
    - >-
      rsync
      --archive
      --compress
      --delete
      --itemize-changes
      --no-group
      --no-owner
      --relative
      -e ssh
      public/app.css
      public/app.js
      public/vendor.js
      www@gailkirklandphotography.com:/var/www/gailkirklandphotography-www
