cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - $BUILD_PATH
    - node_modules/
variables:
  BUILD_PATH: "dist/"
  DEPLOY_HOST: "www@gailkirklandphotography.com"
  DEPLOY_PATH: "/var/www/gailkirklandphotography-www"
  DEPLOY_URL: "$DEPLOY_HOST:$DEPLOY_PATH"
  NODE_ENV: production

build:
  stage: build

  script:
    - npm prune --production=false
    - npm install
    - npm install --only=dev
    - npm list --depth=0 --only=prod
    # this prints both dev and prod
    # TODO: replace with --only=dev when npm issue is resolved
    - npm list --depth=0 --dev
    - npm run build:prod

deploy:
  stage: deploy

  only:
    - tags
  script:
    - >-
      rsync
      --archive
      --compress
      --delete
      --itemize-changes
      --no-group
      --no-owner
      --relative
      -e ssh
      $BUILD_PATH
      $DEPLOY_URL
