cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - public/app.css
    - public/app.js
    - public/vendor.js

build:
  stage: build

  script:
    - npm prune
    - npm install
    - npm list --depth=0
    - NODE_ENV=production npm run build:prod

deploy:
  stage: deploy

  only:
    - master
  script:
    - >-
      rsync
      --archive
      --compress
      --delete
      --itemize-changes
      --no-group
      --no-owner
      --relative
      -e ssh
      public/app.css
      public/app.js
      public/vendor.js
      www@gailkirklandphotography.com:/var/www/gailkirklandphotography-www
