Vagrant.configure(2) do |config|
  if Vagrant.has_plugin?('vagrant-env')
    config.env.enable
  end

  ENV.delete_if {|name, value| value == ''}

  HOSTNAME = ENV['VAGRANT_HOSTNAME'] || 'gailkirklandphotography.localhost'
  MEMORY_SIZE = ENV['MEMORY_SIZE'] || 512
  PORT = ENV['VAGRANT_PORT'] || 8080
  WWW_DIR = ENV['WWW_DIR'] || '/var/www'

  APP_DIR = "#{WWW_DIR}/gailkirklandphotography-www"
  DO_NAME = ENV['DO_NAME'] || HOSTNAME
  DO_SIZE = ENV['DO_SIZE'] || '512mb'

  config.vm.box = 'ubuntu/wily64'
  config.vm.box_check_update = false
  config.vm.hostname = HOSTNAME

  config.vm.provider :digital_ocean do |provider, config|
    config.ssh.private_key_path = '~/.ssh/id_rsa'
    config.vm.box = 'digital_ocean'
    config.vm.box_url = 'https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box'
    config.vm.hostname = DO_NAME

    provider.image = ENV['DO_IMAGE']
    provider.size = DO_SIZE
    provider.ssh_key_name = ENV['DO_SSH_KEY_NAME']
    provider.token = ENV['DO_TOKEN']
  end

  config.vm.provider :virtualbox do |vb|
    vb.name = config.vm.hostname
    vb.memory = MEMORY_SIZE

    config.vm.network 'forwarded_port', {
      auto_correct: true,
      guest: 80,
      host: PORT,
    }

    if Vagrant.has_plugin?('vagrant-cachier')
      config.cache.scope = :box
    end
  end

  config.vm.provision :shell, path: 'node.sh'
  config.vm.provision :shell, {
    env: {
      APP_DIR: APP_DIR,
      HOSTNAME: HOSTNAME,
    },
    path: 'app.sh',
  }

  config.vm.synced_folder 'etc', '/etc', {
    type: 'rsync',
    rsync__args: [
      '--archive',
      '--compress',
    ],
    rsync__chown: false,
  }
  config.vm.synced_folder '..', APP_DIR, {
    type: 'rsync',
    rsync__args: [
      '--archive',
      '--compress',
      '--include=.env',
      '--include=.env.example',
      '--include=dist/***',
      '--include=package.json',
      '--include=public/***',
      '--exclude=*',
      '--progress',
    ],
    rsync__verbose: true,
  }
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
