Vagrant.configure(2) do |config|
  if Vagrant.has_plugin?('vagrant-env')
    config.env.enable
  end

  ENV.delete_if {|name, value| value == ''}

  HOSTNAME = ENV['VAGRANT_HOSTNAME'] || 'gailkirklandphotography.localhost'
  MEMORY_SIZE = ENV['MEMORY_SIZE'] || 512
  PORT = ENV['VAGRANT_PORT'] || 8080
  WWW_DIR = ENV['WWW_DIR'] || '/var/www'

  APP_DIR = "#{WWW_DIR}/#{ENV['REPO_NAME']}"

  config.vm.box = 'ubuntu/wily64'
  config.vm.hostname = HOSTNAME

  config.vm.provider :digital_ocean do |provider, config|
    config.ssh.private_key_path = '~/.ssh/id_rsa'
    config.vm.box = 'digital_ocean'
    config.vm.box_url = 'https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box'
    config.vm.hostname = ENV['DO_NAME'] || HOSTNAME

    provider.image = ENV['DO_IMAGE']
    provider.size = ENV['DO_SIZE'] || '512mb'
    provider.ssh_key_name = ENV['DO_SSH_KEY_NAME']
    provider.token = ENV['DO_TOKEN']
  end

  config.vm.provider :virtualbox do |vb|
    vb.name = config.vm.hostname
    vb.memory = MEMORY_SIZE

    config.vm.network 'forwarded_port', {
      auto_correct: true,
      guest: 80,
      host: PORT,
    }

    if Vagrant.has_plugin?('vagrant-cachier')
      config.cache.scope = :box
    end
  end

  config.vm.provision :shell, {
    env: {
      DOCKER_USERNAME: ENV['DOCKER_USERNAME'],
      DOCKER_PASSWORD: ENV['DOCKER_PASSWORD'],
      DOCKER_REGISTRY: ENV['DOCKER_REGISTRY'],
    },
    path: 'docker.sh',
  }
  config.vm.provision :shell, {
    env: {
      APP_DIR: APP_DIR,
      DOCKER_REGISTRY: ENV['DOCKER_REGISTRY'],
      HOSTNAME: HOSTNAME,
      ORG_NAME: ENV['ORG_NAME'],
      REPO_NAME: ENV['REPO_NAME'],
    },
    path: 'app.sh',
  }

  config.vm.synced_folder 'etc', '/etc', {
    type: 'rsync',
    rsync__args: [
      '--archive',
      '--compress',
    ],
    rsync__chown: false,
  }
  config.vm.synced_folder '..', APP_DIR, {
    type: 'rsync',
    rsync__args: [
      '--archive',
      '--compress',
      '--include=.env',
      '--include=docker-compose*.yml',
      '--exclude=*',
    ],
  }
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
