description: Provides Common Setup for Workflows Dependent on NodeJS
name: setup-node

runs:
  using: composite
  steps:
    - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        cache: npm
        node-version-file: .node-version
    - run: npm ci
      shell: sh
