description: Provides Common Setup for Workflows Dependent on NodeJS
name: setup-node

runs:
  using: composite
  steps:
    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        cache: npm
        node-version-file: .node-version
    - run: npm ci
      shell: sh
