description: Provides Common Setup for Workflows Dependent on NodeJS
name: setup-node

runs:
  using: composite
  steps:
    - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        cache: npm
        node-version-file: .node-version
    - run: npm ci
      shell: sh
