name: build-and-deploy

on:
  pull_request:
    paths:
      - .github/workflows/build-and-deploy.yml
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: ./.github/workflows/setup-node
      - uses: actions/configure-pages@d875fa8dc18209f310fe6999f4cfbc96ee372c2b # tag=v2.1.2
        with:
          static_site_generator: next
      - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - run: npm run build
      - uses: actions/upload-pages-artifact@a597aecd27af1cf14095ccaa29169358e3d91e28 # tag=v1.0.4
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-20.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@69a62cdfa4c32e0d925268597986261876cac577 # tag=v1.2.2
        id: deployment
