name: eslint

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/.eslintrc.yml'
      - .github/workflows/eslint.yml
      - .github/workflows/setup-node/
      - package.json
      - package-lock.json
      - tsconfig.json
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./.github/workflows/setup-node
      - run: npx eslint --ext ts,tsx .
