name: eslint

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/.eslintrc.yml'
      - .github/workflows/eslint.yml
      - .github/workflows/setup-node/
      - package.json
      - package-lock.json
      - tsconfig.json
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - uses: ./.github/workflows/setup-node
      - run: npx eslint --ext ts,tsx .
