name: eslint

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/.eslintrc.yml'
      - .github/workflows/eslint.yml
      - .github/workflows/setup-node/
      - package.json
      - package-lock.json
      - tsconfig.json
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: ./.github/workflows/setup-node
      - run: npx eslint --ext ts,tsx .
