name: eslint

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/.eslintrc.yml'
      - .github/workflows/eslint.yml
      - .github/workflows/setup-node/
      - package.json
      - package-lock.json
      - tsconfig.json
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: ./.github/workflows/setup-node
      - run: npx eslint --ext ts,tsx .
