name: npm

on:
  push:
    paths:
      - .github/workflows/setup-node/
      - .github/workflows/npm.yml
      - package-lock.json

concurrency: npm

jobs:
  npm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - uses: ./.github/workflows/setup-node
