name: npm

on:
  push:
    paths:
      - .github/workflows/setup-node/
      - .github/workflows/npm.yml
      - package-lock.json

concurrency: npm

jobs:
  npm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/workflows/setup-node
