name: skip-required-check

on:
  push:
    paths-ignore:
      - .github/workflows/setup-node/
      - .github/workflows/npm.yml
      - package-lock.json.lock

concurrency: npm

jobs:
  npm:
    runs-on: ubuntu-20.04
    steps:
      - run: echo 'Skipped'
