name: npm

on:
  push:
    paths:
      - .github/workflows/setup-node/
      - .github/workflows/npm.yml
      - package-lock.json

concurrency: npm

jobs:
  npm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: ./.github/workflows/setup-node
